spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    schemas: money_management
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: money_management
        jdbc:
          lob:
            non_contextual_creation: true

services:
  social-circle:
    url: ${SOCIAL_CIRCLE_URL}

storage:
  file:
    path: ${FILE_STORAGE_PATH}

logging:
  file:
    name: ${LOG_PATH}/money_management.log
  level:
    root: WARN
    org:
      springframework:
        web: INFO
      hibernate: ERROR

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${CERTIFICATE_FOLDER}/${KEYSTORE_FILE}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-alias: ${KEY_ALIAS}

ssl:
  trust-store: ${CERTIFICATE_FOLDER}/${KEYSTORE_FILE}
  trust-store-password: ${KEYSTORE_PASSWORD}
